/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufp.sd.boulderdash.client;

import edu.ufp.sd.boulderdash.server.State;
import edu.ufp.sd.boulderdash.server.State.Message;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.rmi.RemoteException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author tiagocardoso
 */
public class BoulderDashClientHallGUI extends javax.swing.JFrame implements WindowListener {

    private BoulderDashClientImpl bdc;

    /**
     * Creates new form BoulderDashClientHallGUI
     */
    public BoulderDashClientHallGUI(BoulderDashClientImpl bdc) throws RemoteException {
        this.bdc = bdc;
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.addWindowListener(this);
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaChatHistory = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        tfMessage = new javax.swing.JTextField();
        lblOnlineUsers = new javax.swing.JLabel();
        jpLobby = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        list1 = new java.awt.List();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpChat.setBorder(javax.swing.BorderFactory.createTitledBorder("Global Chat"));

        jtaChatHistory.setColumns(20);
        jtaChatHistory.setLineWrap(true);
        jtaChatHistory.setRows(5);
        jtaChatHistory.setEnabled(false);
        jScrollPane1.setViewportView(jtaChatHistory);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        tfMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMessageKeyPressed(evt);
            }
        });

        lblOnlineUsers.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblOnlineUsers.setText("Online Clients:");

        javax.swing.GroupLayout jpChatLayout = new javax.swing.GroupLayout(jpChat);
        jpChat.setLayout(jpChatLayout);
        jpChatLayout.setHorizontalGroup(
            jpChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpChatLayout.createSequentialGroup()
                .addComponent(tfMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpChatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOnlineUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpChatLayout.setVerticalGroup(
            jpChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOnlineUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("New Lobby");

        javax.swing.GroupLayout jpLobbyLayout = new javax.swing.GroupLayout(jpLobby);
        jpLobby.setLayout(jpLobbyLayout);
        jpLobbyLayout.setHorizontalGroup(
            jpLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLobbyLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpLobbyLayout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpLobbyLayout.setVerticalGroup(
            jpLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLobbyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lblWelcome.setText("Hello, welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcome)
                    .addComponent(jpLobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() throws RemoteException {
        this.lblWelcome.setText("Hello, welcome " + bdc.getUsername() + "!");
        try {
            this.lblOnlineUsers.setText("Online Clients: " +  this.bdc.bdsRI.countConnectedClients());
        } catch (RemoteException ex) {
            Logger.getLogger(BoulderDashClientHallGUI.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void updateClients() {
        State.ConnectedClients sc = (State.ConnectedClients) this.bdc.getLastState();
        this.lblOnlineUsers.setText("Online Clients: " + sc.getClients());
    }
    
    private void tfMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMessageKeyPressed
        char c = evt.getKeyChar();
        if (c == '\n' || c == '\r') {
            try {
                State.Message ms = new State().new Message(bdc.getUsername(), this.tfMessage.getText(), Calendar.getInstance().getTime());
                this.bdc.bdsRI.setState(ms);
                this.tfMessage.setText("");
            } catch (RemoteException ex) {
                Logger.getLogger(BoulderDashClientHallGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tfMessageKeyPressed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
       try {
            State.Message ms = new State().new Message(bdc.getUsername(), this.tfMessage.getText(), Calendar.getInstance().getTime());
            this.bdc.bdsRI.setState(ms);
            this.tfMessage.setText("");
        } catch (RemoteException ex) {
            Logger.getLogger(BoulderDashClientHallGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    public void updateMesssages() {
        State.Message ms = (State.Message) this.bdc.getLastState();
        String msg = "(" + ms.getOnlyTimeFormatted() +") " + ms.getUsername() + ": " + ms.getMessage();
        this.jtaChatHistory.append(msg + '\n');
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpChat;
    private javax.swing.JPanel jpLobby;
    private javax.swing.JTextArea jtaChatHistory;
    private javax.swing.JLabel lblOnlineUsers;
    private javax.swing.JLabel lblWelcome;
    private java.awt.List list1;
    private javax.swing.JTextField tfMessage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        bdc.triggeredLogout(bdc.getUsername(), bdc.getPassword());
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
